# .github/actions/setup-go/action.yaml
name: Setup Go
description: Checkout, install Go and Dependencies
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: "go.mod"
    - name: Install dependencies
      shell: bash
      run: go mod tidy
