name: Go Lint & Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Install dependencies
        run: go mod tidy
      - name: Run go fmt
        run: go fmt ./...
      - name: Run go vet
        run: go vet ./...
      - name: Run golint
        run: go install golang.org/x/lint/golint@latest && golint ./...
      - name: Run tests
        run: go test -v ./...
